// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { SettingsHealthData, SettingsHealthErrors, SettingsHealthResponses, SettingsProtectedProbeData, SettingsProtectedProbeErrors, SettingsProtectedProbeResponses, SettingsProtectedWriteData, SettingsProtectedWriteErrors, SettingsProtectedWriteResponses, SettingsReadData, SettingsReadErrors, SettingsReadResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Liveness probe.
 */
export const settingsHealth = <ThrowOnError extends boolean = false>(options?: Options<SettingsHealthData, ThrowOnError>): RequestResult<SettingsHealthResponses, SettingsHealthErrors, ThrowOnError> => (options?.client ?? client).get<SettingsHealthResponses, SettingsHealthErrors, ThrowOnError>({ url: '/settings/health', ...options });

/**
 * Role-gated probe (clinician, tenant-admin).
 */
export const settingsProtectedProbe = <ThrowOnError extends boolean = false>(options?: Options<SettingsProtectedProbeData, ThrowOnError>): RequestResult<SettingsProtectedProbeResponses, SettingsProtectedProbeErrors, ThrowOnError> => (options?.client ?? client).get<SettingsProtectedProbeResponses, SettingsProtectedProbeErrors, ThrowOnError>({ url: '/settings/protected', ...options });

/**
 * Demonstration write - actor bound to the JWT principal.
 */
export const settingsProtectedWrite = <ThrowOnError extends boolean = false>(options: Options<SettingsProtectedWriteData, ThrowOnError>): RequestResult<SettingsProtectedWriteResponses, SettingsProtectedWriteErrors, ThrowOnError> => (options.client ?? client).post<SettingsProtectedWriteResponses, SettingsProtectedWriteErrors, ThrowOnError>({
    url: '/settings/protected-write',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Diamond-root scoped read by id.
 */
export const settingsRead = <ThrowOnError extends boolean = false>(options: Options<SettingsReadData, ThrowOnError>): RequestResult<SettingsReadResponses, SettingsReadErrors, ThrowOnError> => (options.client ?? client).get<SettingsReadResponses, SettingsReadErrors, ThrowOnError>({ url: '/settings/{id}', ...options });
