// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://{host}/api/v1/settings' | 'http://localhost:3000' | (string & {});
};

/**
 * Liveness probe result — any authenticated principal may call it.
 */
export type HealthStatus = {
    status: string;
    layer: string;
};

export type ProblemResponse = {
    statusCode?: number;
    status?: number;
    error?: string;
    message: string | Array<string>;
};

/**
 * Scoped single-resource read result.
 */
export type SettingsRead = {
    id: string;
    status: string;
    layer: string;
    actorId: string;
};

export type SettingsWriteInput = {
    /**
     * Optional free-text reason captured on the write. Trimmed runtime-side by Zod.
     */
    reason?: string;
};

/**
 * Result of the demonstration write — actorId is the JWT-derived principal, never body-supplied.
 */
export type WriteAck = {
    status: string;
    layer: string;
    actorId: string;
};

export type SettingsHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/health';
};

export type SettingsHealthErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
};

export type SettingsHealthError = SettingsHealthErrors[keyof SettingsHealthErrors];

export type SettingsHealthResponses = {
    /**
     * The request has succeeded.
     */
    200: HealthStatus;
};

export type SettingsHealthResponse = SettingsHealthResponses[keyof SettingsHealthResponses];

export type SettingsProtectedProbeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/protected';
};

export type SettingsProtectedProbeErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
};

export type SettingsProtectedProbeError = SettingsProtectedProbeErrors[keyof SettingsProtectedProbeErrors];

export type SettingsProtectedProbeResponses = {
    /**
     * The request has succeeded.
     */
    200: HealthStatus;
};

export type SettingsProtectedProbeResponse = SettingsProtectedProbeResponses[keyof SettingsProtectedProbeResponses];

export type SettingsProtectedWriteData = {
    body: SettingsWriteInput;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/settings/protected-write';
};

export type SettingsProtectedWriteErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ProblemResponse;
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
};

export type SettingsProtectedWriteError = SettingsProtectedWriteErrors[keyof SettingsProtectedWriteErrors];

export type SettingsProtectedWriteResponses = {
    /**
     * The request has succeeded.
     */
    200: WriteAck;
};

export type SettingsProtectedWriteResponse = SettingsProtectedWriteResponses[keyof SettingsProtectedWriteResponses];

export type SettingsReadData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/settings/{id}';
};

export type SettingsReadErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
    /**
     * The server cannot find the requested resource.
     */
    404: ProblemResponse;
};

export type SettingsReadError = SettingsReadErrors[keyof SettingsReadErrors];

export type SettingsReadResponses = {
    /**
     * The request has succeeded.
     */
    200: SettingsRead;
};

export type SettingsReadResponse = SettingsReadResponses[keyof SettingsReadResponses];
